server:
  port: 10001

spring:
  application:
    name: canal-client
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 274111